### ISSUE TITLE
Modify svaba-nf to include bwa indexes

### ISSUE THREAD

**Issue by V-Catherine** [IARCbioinfo/svaba-nf#2]
Hi Tiffany,

Could you add the links to the bwa indexes to prevent errors ?
//read files
ref = file(params.ref)
ref_fai = file( params.ref+'.fai' )
ref_sa = file( params.ref+'.sa' )
ref_bwt = file( params.ref+'.bwt' )
ref_ann = file( params.ref+'.ann' )
ref_amb = file( params.ref+'.amb' )
ref_pac = file( params.ref+'.pac' )
ref_alt = file( params.ref+'.alt' )

//in process svaba
input:
	file ref
	file ref_fai
	file ref_sa
	file ref_bwt ++
	file ref_ann ++
	file ref_amb ++
	file ref_pac
	file ref_alt
Thanks :-)

**Comment by tdelhomme** [comment]
Fixed ! add `--options " --override-reference-check "` if your BAM header contains less info than the ref indexes (see our [tests](https://github.com/IARCbioinfo/svaba-nf/blob/master/.circleci/config.yml#L13) for such an example)
